### PR TITLE
Drop Python 3.6 support. Test Python 3.9.

### PR DESCRIPTION
**Pull request by DanAlbert**
Fixes https://github.com/pydcs/dcs/issues/162.

### CODE REVIEW

**Comment by DanAlbert** [comment]
(If you want to let this one sit for a while to see if anyone speaks up on behalf of 3.6 that's fine with me, no urgent need for this)

**Comment by rp-** [comment]
Please update also this here:
https://github.com/pydcs/dcs/blob/2b4eb8bf99d225b37305735773d6504ad844d144/setup.py#L29

**Comment by DanAlbert** [comment]
> Please update also this here:
> https://github.com/pydcs/dcs/blob/2b4eb8bf99d225b37305735773d6504ad844d144/setup.py#L29

Good catch. Done.

**Comment by rp-** [comment]
guess we can drop the change in pythonpackage.yml now?

**Comment by DanAlbert** [comment]
> guess we can drop the change in pythonpackage.yml now?

Huh, I don't remember making the change that was submitted. Not sure what happened there.

I've rebased. I think what I have here is _currently_ the same (always test with the latest python 3 available on in CI), but once 3.10 is available this will silently change behavior, so I've made it explicit.

**Pull request merged**
