### PR TITLE
Support DCS 2.7 cloud presets.

### PR DESCRIPTION
**Pull request by DanAlbert**
In 2.7 cloud presets can be selected, which will:

* Override cloud thickness, density, and precipitation
* Bound the cloud base
* Set the "preset" property in the mission file

This patch adds an import script to load the names and cloud base
boundaries from the config file in the DCS install. The script requires
lupa because the parser in dcs.lua is not capable of parsing complex lua
files (I think it's because there are function calls, but I didn't dig
much).

This also removes the `Weather.fog_density` property, since DCS no
longer supports that.

Fixes https://github.com/pydcs/dcs/issues/118

### CODE REVIEW

**Comment by DanAlbert** [comment]
I'm relatively confident that this is correct. I've added a handful of unit tests but haven't performed an end-to-end test (generate a mission, load in DCS, see clouds) yet. Will do that soon.

**Comment by DanAlbert** [comment]
Have done an end to end test and it all works but I need to make some changes for this to be 3.6 compatible. Forgot I couldn't use `@dataclass` there.

**Comment by DanAlbert** [comment]
Alright, checks are happy now and this is working for Liberation. Ready to merge as far as I'm concerned.

**Comment by SnappyComebacks** [comment]
I'm not sure dust clouds (just below fog in the ME) are supported either.  Have you seen anything on that?

**Comment by rp-** [comment]
One additional thing I would like to have is an `Enum` with all presets, so I could programmatically say
```
from cloud_preset import Clouds
m.weather.set_cloud_preset(Clouds.Preset3)
```
Or maybe we can even generate names from ui_name. e.g.: Clouds.LightScattered1, Clouds.Overcast3...

**Comment by rp-** [comment]
oh, and I'm not sure if we should put `lupa`, into requierements, because it some kind of soft build dependency.
And a usual user of the library wouldn't need it?

**Comment by DanAlbert** [comment]
> because it some kind of soft build dependency.

It'll end up getting run on CI but it won't be used since we don't run the import scripts in CI. Users will install it as part of their dev environment.

I'll go ahead and remove it and just document the requirement for that script since it's not actually a build dependency like you say. It's unfortunate that requirements.txt can't make these sorts of distinctions. Pipenv can but that might be a difficult change.

> And a usual user of the library wouldn't need it?

I think only the `install_requires` field of the `setup.py` matters for that.

> One additional thing I would like to have is an Enum with all presets

Easy enough. Will add that.

> I'm not sure dust smoke (just below fog in the ME) is supported either. Have you seen anything on that?

The changelog says to not do it _right now_. The ME does not prevent it though. Since pydcs is mostly an API for the ME I don't think we need to prevent that (the ME _does_ prevent setting the cloud base outside the bounds, for example).

Eventually a DCS update will fix the fog/dust options when cloud presets are used and this will just start working without needing a pydcs update.

**Comment by DanAlbert** [comment]
Okay, removed from requirements.txt and added the enum. Should be good to go.

**Comment by ColinM9991** [comment]
Out of curiosity, when are we likely to see this merged and released?

**Comment by rp-** [comment]
@DanAlbert are you fine with this small addition? 67e231923e062afa5e0308f6564e83ae313dbfac

**Comment by DanAlbert** [comment]
@rp- yep, looks good!

**Comment by rp-** [comment]
merged with #125

**Pull request closed without merging**
