### PR TITLE
Add strafing task

### PR DESCRIPTION
**Pull request by magwo**
Imitated the bombing task and just adjusted the parameters. Appears to work well for both deserialization and serialization in my manual test.

### CODE REVIEW

**Comment by magwo** [comment]
Closes #337

**Comment by magwo** [comment]
Ping @DanAlbert !
We need this one for our weather generator program. Our training mission has a Strafing task somewhere in it.

**Comment by magwo** [comment]
Just a friendly reminder @DanAlbert in case you missed this. I'm pretty sure it's a safe no-brainer merge. Works well for us currently (using the hash from my fork to build the mizzion buzzer).

**Comment by DanAlbert** [comment]
Last week was a holiday week in the US. Please be patient.

**Comment by magwo** [comment]
I'm sorry @DanAlbert !
I was just worried you might have missed that I created two merge requests, because you handled the other one quickly.

**Pull request merged**
