### PR TITLE
Fix callsign export, update data.

### PR DESCRIPTION
**Pull request by DanAlbert**
Most countries don't actually have their callsigns in a table, the
function db.getCallsign will instead refer to either the US or Russia
table depending on the country. Call that instead.

Also fixed a number of nil dereferences that were occurring.

### CODE REVIEW

**Comment by rp-** [comment]
Just a small thing, can you add your 3 changed flyable modules to the `flyable` set in `pydcs_export.py:235`, so they always be flyable, as this property depends on the owned modules.

**Comment by DanAlbert** [comment]
Done. Was wondering how that worked :)

**Comment by rp-** [comment]
rebased and merged by hand, thanks

**Comment by DanAlbert** [comment]
Sorry, hadn't noticed the conflict. Thanks!

**Comment by rp-** [comment]
There was no conflict, just wanted to keep the history a bit cleaner.
Nothing to worry.

**Pull request closed without merging**
