### PR TITLE
Adding support for additional actions arguments

### PR DESCRIPTION
**Pull request by ucnanoman**
Put additional functionality back in from last release that was taken out.
Tested and this does work.

### CODE REVIEW

**Comment by DanAlbert** [comment]
You mentioned these were removed, but the recent commits that touch that file don't seem to do that. Could you show me where that happened? I'd like to see why they were removed before approving this.

**Comment by ucnanoman** [comment]
I take what I said back, I thought that they were removed.
In reality apparently I had added them to add the extra arguments for actions. 
Example:
trig1.rules.append(dcs.condition.AllOfCoalitionOutsideZone("red", FARPA_capture.id, unit_type="GROUND"))

**Comment by ucnanoman** [comment]
Note: I'm building an application different than DCS Liberation leveraging pydcs, I have quite a few changes.
I'm new to PR and working with other people.
If this is successful, I'll try to ensure I'll only PR things that are useful to everyone (universal).

**Comment by DanAlbert** [comment]
What was the reason for closing this? If it was the inactivity, sorry, I just haven't had a chance to review lately.

**Comment by ucnanoman** [comment]
I have a lot of changes to pydcs that are insignificant to DCS Liberation.
These are just parts that weren't connected up in pydcs I need for my application to work, thought I'd share.
However, I think maybe it's a waste of both of our time since I have to keep a different fork anyway.

**Comment by DanAlbert** [comment]
Liberation might be where I come from but we're certainly not the only user of pydcs :) Any patches that improve pydcs's ability to serialize and deserialize a miz are fair game here as far as I'm concerned.

The branch was deleted so idr exactly, but the PR title makes it sound like it was worth merging here (I just didn't get to it in time). Even if you do want to keep some stuff local to your fork, you'll have an easier time keeping that fork updated if you keep your divergence low. Totally up to you what you contribute, of course, just a suggestion :)

**Comment by bobmoretti** [comment]
After a quick glance at the now-deleted branch, the changes there seem valuable.

https://github.com/pydcs/dcs/commit/0d99635b3c70698ca81795564ef02f29137e0733

Could we revive this PR and land it in pydcs?

**Comment by ucnanoman** [comment]
Alright since you guys are interested and such i'll start pulling in my changes and doing pull requests when I get back from this trip.

**Pull request closed without merging**
