### PR TITLE
Export DCS 2.8

### PR DESCRIPTION
**Pull request by Raffson**
Introduces the MB-339

### CODE REVIEW

**Comment by Raffson** [comment]
Commented out everything related to `Ka_50_3` in `countries.py` since there's no such helicopter being exported to `helicopters.py`. I assume this is preliminary stuff from ED for the black shark 3 upgrade.

**Comment by DanAlbert** [comment]
> Commented out everything related to Ka_50_3 in countries.py

Manually? The export script will need to be fixed.

**Comment by DanAlbert** [comment]
(if not manually, just omit those lines during export rather than the commented lines)

**Comment by Raffson** [comment]
> Manually? The export script will need to be fixed.

Adding `Ka_50_3` to `countryHeliIgnore` did the trick.

**Comment by Raffson** [comment]
While at it, should `MB_339A` be removed from `countryPlaneIgnore`?

**Comment by DanAlbert** [comment]
That seems likely. Good catch.

**Comment by Raffson** [comment]
Should be ready 👍

**Pull request merged**
