### PR TITLE
Add 'dot2' and 'solid2' to LineStyle enum

### PR DESCRIPTION
**Pull request by bobmoretti**

### CODE REVIEW

**Comment by adamdoda** [comment]
Hi @rp- @DanAlbert
Could you merge this please? kinda blocking project-tauntaun.

**Comment by rp-** [comment]
sorry kinda missed that

**Comment by bobmoretti** [comment]
Thank you!!

**Comment by DanAlbert** [comment]
I also completely missed the original email. Thanks for pinging :)

**Pull request merged**
